site_name: Подготовка к демоэкзамену ГДРМИ

use_directory_urls: false

theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/logo.png
  language: ru
  features:
    - content.code.copy     # кнопка "копировать"
    - content.image.zoom    # zoom картинок
    - navigation.top        # "наверх"
    - navigation.tracking   # подсветка активного пункта в правом TOC
    - toc.follow            # правый TOC следует за прокруткой

plugins:
  - glightbox
  - search

nav:
    - Главная: index.md
    - Теория:
      - HTML и CSS: theory/html_css.md
      - JavaScript: theory/javascript.md
      - Серверная часть: theory/server_side.md
      - Базы данных: theory/databases.md
    - Модуль 1. Проектирование и разработка информационных систем:
      - Описание задания: module1/index.md
      - Пример решения: module1/example_solution.md
    - Модуль 2. Разработка дизайна веб-приложений:
      - Описание задания: module2/index.md
      - Пример решения: module2/example_solution.md
    - Модуль 3. Проектирование, разработка и оптимизация веб-приложений:
      - Описание задания: module3/index.md
      - Пример решения: module3/example_solution.md

    # Добавьте свои разделы и страницы здесь

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/js/mermaid-init.js

extra_css:
  - assets/stylesheets/extra.css
